package VueControlleur;
import Modele.*;
import GestionDomaine.*;
import GestionGlobal.Clavier;
import java.util.*;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
/**
 *
 * @author svv
 */
public class MenuAgent extends javax.swing.JFrame {
    
      GestionPersonne gp;
    GestionReservation gr;
    GestionVol gv;
    GestionPaiement gpaie;
    private String [] liste; //La liste des clients et des passagers
    private String[] listeA;// Les réservations dont l'acompte n'est pas payé et délai passé
    private String[] listeT; //les réservations dont la totalite n'est pas payé et délai passé
    private String[] listeC;
    private String[] listeV;
    private int nb;
    private int nba;
    private int nbt;
    private int nbc;
    private int nbv;
    private int selection;
    
    public MenuAgent(GestionPersonne gp,GestionReservation gr,GestionVol gv,GestionPaiement gpaie) {
        initComponents();
        /*GestionReservation gr = new GestionReservation();
        GestionVol gv = new GestionVol();
        GestionPaiement gp = new GestionPaiement();
        */
        this.gp=gp;
       this.gr=gr;
       this.gv=gv;
       this.gpaie=gpaie;
        liste = new String[200];
        AfficherCliPas.setListData(liste);
        listeA = new String[200];
        jList1.setListData(listeA);
        listeT = new String[200];
        jList5.setListData(listeT);
         listeC = new String[200];
        jList5.setListData(listeC);
         listeV = new String[200];
        ListeVols.setListData(listeC);
        selection = -1;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NumRes = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        afficherCliPas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AfficherCliPas = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        SupResA = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        affMontantResD = new javax.swing.JTextField();
        MontantResD = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        AfficherCliA = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        AfficherCliT = new javax.swing.JButton();
        AnnulRes = new javax.swing.JButton();
        RetourMenuAge = new javax.swing.JButton();
        AffCliA = new javax.swing.JButton();
        Result = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList5 = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        NumVol = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        NbrReservation = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        ListeVols = new javax.swing.JList<>();
        AnnulerVol = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        ClasseVolSaisi = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        VilleDep = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        DateDepmm = new javax.swing.JTextField();
        VilleArr = new javax.swing.JTextField();
        StatutVol = new javax.swing.JTextField();
        DateArrmm = new javax.swing.JTextField();
        NomCom = new javax.swing.JTextField();
        DateDepjj = new javax.swing.JTextField();
        DateArryyyy = new javax.swing.JTextField();
        DateArrjj = new javax.swing.JTextField();
        DateDepyyyy = new javax.swing.JTextField();
        CreerVol1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Afficher les clients et les passagers d'un numéro de réservation donnée --->");

        jLabel2.setText("Numéro de réservation :");

        afficherCliPas.setText("Afficher");
        afficherCliPas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afficherCliPasActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(AfficherCliPas);

        jLabel3.setText("Afficher et supprimer les réservations dont l'acompte n'est pas payé et délai passé");

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        SupResA.setText("Supprimer");
        SupResA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupResAActionPerformed(evt);
            }
        });

        jLabel4.setText("Montant des réservations pour une destination");

        jLabel5.setText("Destination");

        affMontantResD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                affMontantResDActionPerformed(evt);
            }
        });

        MontantResD.setText("Afficher");
        MontantResD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MontantResDActionPerformed(evt);
            }
        });

        jLabel10.setText("Afficher les clients n'ayant payé qu'un acompte de 30%");

        jScrollPane4.setViewportView(jList3);

        AfficherCliA.setText("Afficher");
        AfficherCliA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AfficherCliAActionPerformed(evt);
            }
        });

        jLabel12.setText("Afficher et supprimer les réservations dont la totalité n'est pas payé et délai passé");

        AfficherCliT.setText("Afficher");
        AfficherCliT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AfficherCliTActionPerformed(evt);
            }
        });

        AnnulRes.setText("Annuler");
        AnnulRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulResActionPerformed(evt);
            }
        });

        RetourMenuAge.setText("Retour");
        RetourMenuAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetourMenuAgeActionPerformed(evt);
            }
        });

        AffCliA.setText("Afficher");
        AffCliA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AffCliAActionPerformed(evt);
            }
        });

        Result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultActionPerformed(evt);
            }
        });

        jList5.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(jList5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(RetourMenuAge, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(9, 9, 9))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(AffCliA, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(510, 510, 510)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(AfficherCliT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(AnnulRes, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(151, 151, 151))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(AfficherCliA, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(44, 44, 44)
                                                .addComponent(SupResA))
                                            .addComponent(jLabel1))
                                        .addGap(181, 181, 181)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(NumRes, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(afficherCliPas, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(affMontantResD, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(MontantResD, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(Result, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(NumRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(afficherCliPas))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(AfficherCliA)
                                    .addComponent(SupResA))
                                .addGap(17, 17, 17)
                                .addComponent(jLabel12))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AfficherCliT)
                            .addComponent(AnnulRes))
                        .addGap(17, 17, 17)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(affMontantResD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MontantResD)
                            .addComponent(Result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)))
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(AffCliA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(RetourMenuAge))
        );

        jTabbedPane1.addTab("Reservations", jPanel1);

        jLabel6.setText("Numéro de vol");

        jLabel7.setText("Nb de réservations pour un vol par classe");

        NbrReservation.setText("Afficher");
        NbrReservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NbrReservationActionPerformed(evt);
            }
        });

        jLabel8.setText("Montant de réservations pour un vol");

        jButton6.setText("Afficher");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        ListeVols.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListeVolsMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(ListeVols);

        AnnulerVol.setText("Annuler un vol");
        AnnulerVol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerVolActionPerformed(evt);
            }
        });

        jLabel9.setText("Modifier le prix d'un vol ?");

        jButton9.setText("Retour");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel11.setText("Classe : 1-économique, 2-affaire, 3-première");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(NumVol, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(NbrReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ClasseVolSaisi, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AnnulerVol)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(NumVol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(ClasseVolSaisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NbrReservation)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(AnnulerVol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addGap(17, 17, 17))
        );

        jTabbedPane1.addTab("Gestion Vols", jPanel2);

        jLabel13.setText("Numéro de vol");

        jLabel14.setText("Ville d'arrivée");

        jLabel15.setText("Ville de départ");

        jLabel16.setText("Date de départ");

        jLabel17.setText("Statut vol");

        jLabel18.setText("Date d'arrivée");

        jLabel19.setText("Nom compagnie");

        DateDepmm.setText("mm");

        DateArrmm.setText("mm");

        DateDepjj.setText("jj");

        DateArryyyy.setText("yyyy");

        DateArrjj.setText("jj");

        DateDepyyyy.setText("yyyy");
        DateDepyyyy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateDepyyyyActionPerformed(evt);
            }
        });

        CreerVol1.setText("Créer Vol");
        CreerVol1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreerVol1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DateArrjj, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DateDepjj, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DateArrmm, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(DateDepmm, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DateDepyyyy, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DateArryyyy, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(CreerVol1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(VilleArr, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(VilleDep, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(StatutVol, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NomCom, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(545, 545, 545))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(VilleDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(VilleArr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(DateDepmm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateDepjj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateDepyyyy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(DateArrmm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateArrjj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateArryyyy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(StatutVol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(NomCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(CreerVol1)
                .addContainerGap(193, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Creer Vol", jPanel3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 823, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        this.toBack();
        setVisible(false);
        new MenuPrincipale().toFront();
        new MenuPrincipale().setState(java.awt.Frame.NORMAL);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void AnnulerVolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerVolActionPerformed
        Vol vol;
        
       
        if(selection>=1){//ceci permet de selectionner un vol déjà présent dans la liste
             //RechercherVol:
             vol=gv.getListVols().get(selection);
            boolean bo=gv.supprimerVol(vol);//ensuite il faut changer le statut de ce vol séléctionné à False
            if(bo==true){
                JOptionPane.showConfirmDialog(null,"La supression d'un vol est effectué","Confirmation",JOptionPane.OK_OPTION);  
            }
        }
    }//GEN-LAST:event_AnnulerVolActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void NbrReservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NbrReservationActionPerformed
        PlaceClasse classe;
        ArrayList<Reservation> listRes;
        
        String p=ClasseVolSaisi.getText();
        int n=Integer.parseInt(p);
        String vol=NumVol.getText();
        int i=Integer.parseInt(vol);

        Vol v=gv.rechercherVol(i);
        PlaceClasse pc=gv.rechercherClasse(v, n);//La classe

        listRes=gr.afficherResClasse(pc);

        //listRes.size());
    }//GEN-LAST:event_NbrReservationActionPerformed

    private void ResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultActionPerformed

    }//GEN-LAST:event_ResultActionPerformed

    private void AffCliAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AffCliAActionPerformed
        Reservation r;
        boolean bo;
        double montantPaye;
        ArrayList<Reservation> listR= gr.getListReservation();

        for(int i=0;i<listR.size();i++){
            r=listR.get(i);
            montantPaye=gpaie.calculerMontant(r);
            if(montantPaye!=r.getMontantRes()){
                listeC[nbc] = r.getClient().getId() + " " + r.getClient().getNom() + " " + r.getClient().getPrenom() + " " + r.getClient().getAdresseMail();
                jList3.setListData(listeC);
                nbc++;
            }
        }
    }//GEN-LAST:event_AffCliAActionPerformed

    private void RetourMenuAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetourMenuAgeActionPerformed
        this.toBack();
        setVisible(false);
        new MenuPrincipale().toFront();
        new MenuPrincipale().setState(java.awt.Frame.NORMAL);
    }//GEN-LAST:event_RetourMenuAgeActionPerformed

    private void AnnulResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulResActionPerformed
        Reservation r;
        boolean bo;
        ArrayList<Reservation> listR= gr.getListReservation();

        for(int i=0;i<listR.size();i++){
            r=listR.get(i);
            bo=gpaie.verifierTotalite(r);
            DefaultListModel lstModel = (DefaultListModel) jList1.getModel();

            if(jList1.getSelectedIndex()==1){
                if(bo==false){//need to perform on selected item in liste
                    r.setStatutRes(false);
                }
            }
        }
    }//GEN-LAST:event_AnnulResActionPerformed

    private void AfficherCliTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AfficherCliTActionPerformed
        Reservation r;
        boolean bo;
        double montantPaye;
        ArrayList<Reservation> listR= gr.getListReservation();
    for(int i=0;i<listR.size();i++){
                   r=listR.get(i); 
                   bo=gpaie.verifierTotalite(r);
                   if(bo==false){//la totalite(70%) n'a pas été payé dans le delais
                  //Afficher les infos sur les reservations
                   listeT[nbt]=""+r.getNumReservation()+" "+" "+r.getMontantRes()+" "+r.getClasse();
                    jList5.setListData(listeT);
                    nbt++;
                }
              }
        
    
        
    }//GEN-LAST:event_AfficherCliTActionPerformed
//Afficher les réservations dont l'acompte n'est pas payé et délai passé
    private void AfficherCliAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AfficherCliAActionPerformed
        Reservation r;
        boolean bo;
        double montantPaye;
        ArrayList<Reservation> listR= gr.getListReservation();

        for(int i=0;i<listR.size();i++){
            r=listR.get(i);
            montantPaye=gpaie.calculerMontant(r);
            if(montantPaye==0){
                listeA[nba] = r.getClient().getId() + " " + r.getClient().getNom() + " " + r.getClient().getPrenom() + " " + r.getClient().getAdresseMail();
                jList1.setListData(listeA);
                nba++;
            }

        }
    }//GEN-LAST:event_AfficherCliAActionPerformed

    private void MontantResDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MontantResDActionPerformed
        ArrayList<Vol> listVols;
        ArrayList<Reservation> listRes;
        double somme=0;
        double montant;

        String d=affMontantResD.getText();

        listVols=gv.afficherVolsDes(d);
        listRes=gr.afficherResVols(listVols);

        for(int i=0;i<listRes.size();i++){
            montant=listRes.get(i).getMontantRes();
            somme=somme+montant;
            String s = evt.getActionCommand();
            if (s.equals("MontantResD")) {
                Result.setText("somme");
            }
        }
    }//GEN-LAST:event_MontantResDActionPerformed

    private void affMontantResDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_affMontantResDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_affMontantResDActionPerformed

    private void SupResAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupResAActionPerformed
        DefaultListModel lstModel = (DefaultListModel) jList1.getModel();

        if(jList1.getSelectedIndex()==1){
            lstModel.removeElementAt(jList1.getSelectedIndex());
        }
    }//GEN-LAST:event_SupResAActionPerformed
// 
    private void afficherCliPasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afficherCliPasActionPerformed
        Client c;
        Passager p;
        Reservation r;
        ArrayList<Passager> listP;

        String nr=NumRes.getText();
        int j=Integer.parseInt(nr);
        r=gr.rechercherReservation(j);
        int n;

        if(r!=null){

            c=r.getClient();
            listP=r.getListePassagers();
            for(int i=0;i<listP.size();i++){
                liste[nb] = c.getId() + " " + c.getNom() + " " + c.getPrenom() + " " + c.getAdresseMail()+ " " + listP.get(i).getId()+ " " + listP.get(i).getNom()+ " " + listP.get(i).getPrenom()+ " " +listP.get(i).getAdresseMail();
                AfficherCliPas.setListData(liste);
                nb++;
            }

        }
    }//GEN-LAST:event_afficherCliPasActionPerformed

    private void DateDepyyyyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateDepyyyyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateDepyyyyActionPerformed
//Creer vol
    private void CreerVol1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreerVol1ActionPerformed
        String numv = NumVol.getText();
        int i = Integer.parseInt(numv);
        String vd = VilleDep.getText();
        String va = VilleArr.getText();
        String depj  = DateDepjj.getText();
        int jd=Integer.parseInt(depj);
        String depm  = DateDepmm.getText();
        int md=Integer.parseInt(depm);
        String depy  = DateDepyyyy.getText();
        int ad=Integer.parseInt(depy);
        Date dateDepart=new Date(ad-1900,md-1,jd);
        String arrj  = DateArrjj.getText();
        int ja=Integer.parseInt(arrj);
        String arrm  = DateArrmm.getText();
        int ma=Integer.parseInt(arrm);
        String arry  = DateArryyyy.getText();
        int aa=Integer.parseInt(arry);
        Date dateArrive=new Date(aa-1900,ma-1,ja);
        String stat = StatutVol.getText();
        boolean b = Boolean.parseBoolean(stat);
        String nc = NomCom.getText();
        
        Vol v=gv.creerVol(i, vd, va, dateDepart, dateArrive, b, nc);
     
        listeV[nbv] = v.getNumVol() + " " + v.getVilleDepart() + " " + v.getVilleArrivee() + " " + v.getDateDepart()+ " " + v.getDateArrivee()+ " " + v.isStatutVol()+ " " + v.getNomCompagnie();
        ListeVols.setListData(listeV);
        
         nbv++;
   
    }//GEN-LAST:event_CreerVol1ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jList1MouseClicked
//Cliquer sur un des vols pour le supprimer 
    private void ListeVolsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListeVolsMouseClicked
       int i=ListeVols.getSelectedIndex();
       selection=i;
    }//GEN-LAST:event_ListeVolsMouseClicked

                                                                   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MenuAgent().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AffCliA;
    private javax.swing.JButton AfficherCliA;
    private javax.swing.JList<String> AfficherCliPas;
    private javax.swing.JButton AfficherCliT;
    private javax.swing.JButton AnnulRes;
    private javax.swing.JButton AnnulerVol;
    private javax.swing.JTextField ClasseVolSaisi;
    private javax.swing.JButton CreerVol1;
    private javax.swing.JTextField DateArrjj;
    private javax.swing.JTextField DateArrmm;
    private javax.swing.JTextField DateArryyyy;
    private javax.swing.JTextField DateDepjj;
    private javax.swing.JTextField DateDepmm;
    private javax.swing.JTextField DateDepyyyy;
    private javax.swing.JList<String> ListeVols;
    private javax.swing.JButton MontantResD;
    private javax.swing.JButton NbrReservation;
    private javax.swing.JTextField NomCom;
    private javax.swing.JTextField NumRes;
    private javax.swing.JTextField NumVol;
    private javax.swing.JTextField Result;
    private javax.swing.JButton RetourMenuAge;
    private javax.swing.JTextField StatutVol;
    private javax.swing.JButton SupResA;
    private javax.swing.JTextField VilleArr;
    private javax.swing.JTextField VilleDep;
    private javax.swing.JTextField affMontantResD;
    private javax.swing.JButton afficherCliPas;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList3;
    private javax.swing.JList<String> jList5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
